// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: gmgzgcomyhnrayugbajc

class SupabaseConfig {
  static const String supabaseUrl = 'https://gmgzgcomyhnrayugbajc.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtZ3pnY29teWhucmF5dWdiYWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NDcyMTksImV4cCI6MjA3ODAyMzIxOX0.NJ69at18sF77MUkd0dhDTpCllzmB8eANMg-IFgwubrQ';
}
